version: '3'

services: 
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment: 
      - ENV=development
    ports:
      - 80:80
    networks: 
      - app-network


  default:
    container_name: default
    build: ./color-service
    networks: 
      - app-network

  number:
    container_name: number-service
    build: ./number-service
    networks: 
      - app-network

  blue:
    container_name: blue
    build: ./color-service
    environment: 
      - COLOR=blue
    networks: 
      - app-network

  green:
    container_name: green
    build: ./color-service
    environment: 
      - COLOR=green
    networks: 
      - app-network

  red:
    container_name: red
    build: ./color-service
    environment: 
      - COLOR=red
    networks: 
      - app-network

networks: 
  app-network:
